
oneup_uploader:
    chunks:
        maxage:               604800
        storage:
            type:               filesystem
            directory:          ~
            filesystem:         ~
            sync_buffer_size:   100K
            stream_wrapper:     ~
            prefix:             'chunks'
        load_distribution:    true
    orphanage:
        maxage:               604800
        directory:            ~
    twig:                 true
    mappings:             # Required
        carrousel:
            frontend:             dropzone
            namer:                oneup_uploader.namer.uniqid
            storage:
                directory: "%kernel.root_dir%/../public/uploads/"

        # Prototype
        id:
            frontend:             dropzone
            custom_frontend:
                name:                 ~
                class:                ~
            storage:
                service:              ~
                type:                 filesystem
                filesystem:           ~
                directory:            ~
                stream_wrapper:       ~
                sync_buffer_size:     100K
            route_prefix:
            endpoints:
                upload: ~
                progress: ~
                cancel: ~
            allowed_mimetypes:     []
            disallowed_mimetypes:  []
            error_handler:        oneup_uploader.error_handler.noop
            root_folder:          false

            # Set max_size to -1 for gracefully downgrade this number to the systems max upload size.
            max_size:             9223372036854775807
            use_orphanage:        false
            enable_progress:      false
            enable_cancelation:   false
            namer:                oneup_uploader.namer.uniqid
